#!/bin/bash

function spacemacsrepo () {
  local repo_dev=https://github.com/syl20bnr/spacemacs/tree/develop

  if [ $# -eq 0 ]; then
    open "${repo_dev}"
  elif [ $1 = "lang" ]; then
    if [ $# -eq 1 ]; then
      open "${repo_dev}/layers/%2Blang"
    else
      open "${repo_dev}/layers/%2Blang/${2}"
    fi
  else
    open "${repo_dev}"
  fi
}

function checkoutmaster () {
  local current_branch=$(git branch | rg '\*' | cut -c 3-)
  if [ "${current_branch}" = "master" ]; then
    echo "Already on 'master'"
    return 0
  fi

  local diff=$(git diff | wc -l)

  if [ "${diff}" = "0" ]; then
    git checkout master
    return 0
  fi

  git add -A
  git commit -m "tmp commit; Don't push remote"

  git checkout master
  return 0
}

function atcodergen () {
  local atcoderdir="${HOME}/src/github.com/shhr1214/atcoder"
  local name="$1"

  if [ "${name}" = "" ]; then
    echo "name を引数にいれて"
    return 1
  fi

  if [ -e "${atcoderdir}/${name}" ]; then
    echo "その名前のプロジェクトはすでにあるぞ"
    return 1
  fi

  if [ ! -e "${atcoderdir}" ]; then
    mkdir -p "${atcoderdir}"
  fi

  cd "${atcoderdir}"
  cargo generate \
        --git https://github.com/rust-lang-ja/atcoder-rust-base \
        --branch ja \
        --name "${name}"
  cd "${name}"
}
