#!/bin/bash

function spacemacsrepo () {
  local repo_dev=https://github.com/syl20bnr/spacemacs/tree/develop

  if [ $# -eq 0 ]; then
    open "${repo_dev}"
  elif [ $1 = "lang" ]; then
    if [ $# -eq 1 ]; then
      open "${repo_dev}/layers/%2Blang"
    else
      open "${repo_dev}/layers/%2Blang/${2}"
    fi
  else
    open "${repo_dev}"
  fi
}

function checkoutmaster () {
  local current_branch=$(git branch | rg '\*' | cut -c 3-)
  if [ "${current_branch}" = "master" ]; then
    echo "Already on 'master'"
    return 0
  fi

  local diff=$(git diff | wc -l)

  if [ "${diff}" = "0" ]; then
    git checkout master
    return 0
  fi

  git add -A
  git commit -m "tmp commit; Don't push remote"

  git checkout master
  return 0
}

