all:

setup:
	ln -fs ${DOTFILES}/shell/.bash_profile ${HOME}/.bash_profile
	ln -fs ${DOTFILES}/shell/.bashrc ${HOME}/.bashrc
	ln -fs ${DOTFILES}/shell/.zshenv ${HOME}/.zshenv
	ln -fs ${DOTFILES}/shell/.zshrc ${HOME}/.zshrc

remove:
	rm ${HOME}/.bash_profile
	rm ${HOME}/.bashrc
	rm ${HOME}/.zshenv
	rm ${HOME}/.zshrc
