# zmodload zsh/zprof && zprof

. "${HOME}"/.nix-profile/etc/profile.d/nix.sh

autoload -Uz run-help
autoload -Uz add-zsh-hook
autoload -Uz colors && colors
autoload -Uz is-at-least
autoload -Uz vcs_info

fpath+="${HOME}"/.zfunc
autoload -Uz compinit && compinit -u

# 補完の大文字小文字区別
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}'

typeset -U path PATH

export LANGUAGE="en_US.UTF-8"
export LANG="${LANGUAGE}"
export LC_ALL="${LANGUAGE}"
export LC_CTYPE="${LANGUAGE}"

export EDITOR="nvim -u NONE --noplugin"
export CVSEDITOR="${EDITOR}"
export GIT_EDITOR="${EDITOR}"

export PAGER=less
export LESSCHARSET='utf-8'

export HISTFILE="${HOME}"/.zsh_history
export HISTSIZE=10000
export SAVEHIST=1000000
export LISTMAX=50

export XDG_CONFIG_HOME="${HOME}"/.config
source "${HOME}"/.dotfiles/tools/env.zsh
source "${HOME}"/.dotfiles/editor/env.zsh
source "${HOME}"/.dotfiles/lang/env.zsh
