# zmodload zsh/zprof && zprof

if [[ "$(uname)" == "Darwin" ]]; then
  export OS_TYPE="macos"
  export PATH="/usr/local/sbin:/usr/local/bin:${PATH}"
else
  echo "現在 macos 以外対応してない"
  export OS_TYPE="unknown"
  export NIX_IGNORE_SYMLINK_STORE=1
  . "${HOME}/.nix-profile/etc/profile.d/nix.sh"
fi

typeset -U path PATH

export LANGUAGE="en_US.UTF-8"
export LANG="${LANGUAGE}"
export LC_ALL="${LANGUAGE}"
export LC_CTYPE="${LANGUAGE}"

export XDG_CONFIG_HOME="${HOME}/.config"
export XDG_CACHE_HOME="${HOME}/.cache"
export XDG_DATA_HOME="${HOME}/.local/share"
export ZDOTDIR="${XDG_CONFIG_HOME}/zsh"

export HISTFILE="${XDG_DATA_HOME}/zsh/history"
export HISTSIZE=10000
export SAVEHIST=1000000
export LISTMAX=50

autoload -Uz run-help
autoload -Uz add-zsh-hook
autoload -Uz colors && colors
autoload -Uz is-at-least
autoload -Uz vcs_info

fpath+="${ZDOTDIR}/func"
autoload -Uz compinit && compinit -d "${ZDOTDIR}/.zcompdump"

# 補完の大文字小文字区別
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}'

source "${HOME}/.dotfiles/tools/env.zsh"
source "${HOME}/.dotfiles/lang/env.zsh"
