#!/bin/bash

# nix https://nixos.org/nix/
curl https://nixos.org/nix/install | sh
nix-channel --add https://nixos.org/channels/nixpkgs-unstable
nix-channel --update
nix-env -iA nixpkgs.cachix
cachix use all-hies

nix-env --install openssl

if [[ "$OSTYPE" == "darwin"* ]]; then
  /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi
