#!/bin/bash

toolsdir="${HOME}/.dotfiles/tools"

mkdir -p "${XDG_CONFIG_HOME}/git"
mkdir -p "${XDG_CONFIG_HOME}/alacritty"
mkdir -p "${XDG_DATA_HOME}/tig"

ln -fs "${toolsdir}/gitconfig"      "${XDG_CONFIG_HOME}"/git/config
ln -fs "${toolsdir}/alacritty.yml"  "${XDG_CONFIG_HOME}"/alacritty/alacritty.yml
ln -fs "${toolsdir}/starship.toml"  "${XDG_CONFIG_HOME}"/starship.toml
ln -fs "${toolsdir}/karabiner.json" "${XDG_CONFIG_HOME}"/karabiner/karabiner.json

touch "${XDG_CONFIG_HOME}/git/config.local"
