#!/bin/bash

nix-env --install zsh
nix-env --install tmux

ln -fs "${HOME}"/.dotfiles/shell/bash_profile "${HOME}"/.bash_profile
ln -fs "${HOME}"/.dotfiles/shell/bashrc       "${HOME}"/.bashrc
ln -fs "${HOME}"/.dotfiles/shell/zshenv       "${HOME}"/.zshenv
ln -fs "${HOME}"/.dotfiles/shell/zshrc        "${HOME}"/.zshrc
ln -fs "${HOME}"/.dotfiles/shell/tmux.conf    "${HOME}"/.tmux.conf
ln -fs "${HOME}"/.dotfiles/shell/nixpkgs      "${HOME}"/.config/nixpkgs

source .zshrc

