add_newline = false

[aws]
disabled = true

[golang]
symbol = ' '

[package]
symbol = ' '

[python]
python_binary = ["python3", "python", "python2"]
symbol = ' '

[ruby]
symbol = ' '

[rust]
symbol = ' '
