#!/bin/bash

if [[ "$(uname)" == "Darwin" ]]; then
  export OS_TYPE="macos"
else
  echo "現在 macos 以外対応してない"
  exit 1
fi

/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
(cd "${HOME}/.dotfiles/tools" && brew bundle)
tic -x -o "${HOME}/.terminfo" "${HOME}/.dotfiles/shell/xterm-24bit.terminfo"

if [ ! -e "${HOME}/.cargo" ]; then
    curl https://sh.rustup.rs -sSf | sh
fi
