#!/bin/bash

if [[ "$(uname)" == "Darwin" ]]; then
  export OS_TYPE="macos"
else
  echo "現在 macos 以外対応してない"
  export OS_TYPE="unknown"
fi

/bin/bash "${HOME}/.dotfiles/tools/script/bootstrap"
/bin/bash "${HOME}/.dotfiles/shell/script/bootstrap"
/bin/bash "${HOME}/.dotfiles/lang/script/bootstrap"
