#!/bin/bash

if [[ "$(uname)" == "Darwin" ]]; then
  export OS_TYPE="macos"
else
  echo "現在 macos 以外対応してない"
  export OS_TYPE="unknown"
fi

(cd "${HOME}/.dotfiles" && git pull)
if [[ $? -ne 0 ]]; then
  echo "failed to udpate .dotfiles"
  exit 1
fi


/bin/bash "${HOME}/.dotfiles/tools/script/update"
/bin/bash "${HOME}/.dotfiles/shell/script/update"
/bin/bash "${HOME}/.dotfiles/lang/script/update"
/bin/bash "${HOME}/.dotfiles/editor/script/update"
