#!/bin/bash
cd ${HOME}/.dotfiles && git pull

bash ${HOME}/.dotfiles/shell/script/update
bash ${HOME}/.dotfiles/lang/script/update
bash ${HOME}/.dotfiles/editor/script/update
bash ${HOME}/.dotfiles/tools/script/update
