#!/bin/bash

repo="${HOME}/.dotfiles/private/rust-analyzer"

if [ -e "${repo}" ]; then
  cd "${repo}"
  git pull
else
  git clone https://github.com/rust-analyzer/rust-analyzer "${repo}"
  cd "${repo}"
fi

cargo xtask install --server
