#!/bin/bash

hie_path="${HOME}/.dotfiles/private/haskell-ide-engine"

if [ -e "${hie_engine}" ]; then
  cd "${hie_engine}"
  git pull
else
  git clone https://github.com/haskell/haskell-ide-engine --recurse-submodules "${hie_engine}"
  cd "${hie_engine}"
fi

stack ./install.hs hie
