#!/bin/bash

python -m ensurepip --default-pip --user
pip install --upgrade --user pip
pip install --user autoflake
pip install --user bashate
pip install --user black
pip install --user coverage
pip install --user cython
pip install --user epc
pip install --user flake8
pip install --user importmagic
pip install --user isort
pip install --user jupyter_contrib_nbextensions
pip install --user neovim
pip install --user ptvsd
pip install --user pyls-black
pip install --user pyls-isort
pip install --user pyls-mypy
pip install --user pynvim
pip install --user python-language-server
pip install --user scikit-learn
pip install --user yapf

jupyter contrib nbextension install --user

ln -fs "${HOME}/.dotfiles/lang/mypy"     "${XDG_CONFIG_HOME}/mypy"
ln -fs "${HOME}/.dotfiles/lang/pylintrc" "${XDG_CONFIG_HOME}/pylintrc"
