#!/bin/bash

rustup self update
rustup update
rustup component add rls
rustup component add rust-analysis
rustup component add rust-src
rustup component add rustfmt
rustup component add clippy
mkdir -p "${ZDOTDIR}/func"
rustup completions zsh > "${ZDOTDIR}/func/_rustup"
