#!/bin/bash

rustup self update
rustup update
rustup component add rls
rustup component add rust-analysis
rustup component add rust-src
rustup component add rustfmt
rustup component add clippy
mkdir -p "${HOME}/.zfunc"
rustup completions zsh > "${HOME}/.zfunc/_rustup"
