#!/bin/bash

# rust
rustup self update
rustup update
rustup component add rls
rustup component add rust-analysis
rustup component add rust-src
rustup component add rustfmt
rustup component add clippy
rustup completions zsh > ~/.zfunc/_rustup

cargo install racer
cargo install cargo-edit
mkdir "${HOME}"/.zfunc

# script
nix-env --install ShellCheck
yarn global add bash-language-server
pip install --user bashate

# haskell
nix-env --install stack
nix-env --install ghc
stack install apply-refact hlint stylish-haskell hasktags hoogle hindent
nix-env -iA selection --arg selector 'p: { inherit (p) ghc865; }' -f https://github.com/infinisil/all-hies/tarball/master

# ocaml
nix-env --install opam
opam init
opam config setup -a
opam install merlin utop ocp-indent
opam user-setup install

# c/c++
nix-env --install ccls

# jvm familiy
nix-env --install adoptopenjdk-openj9-bin
nix-env --install clojure
nix-env --install kotlin
nix-env --install boot
nix-env --install leiningen
nix-env --install sbt
yarn global add lumo-cljs

# elixir
nix-env --install elixir

# go
nix-env --install go
nix-env --install delve

# javascript / web
yarn global add typescript typescript-language-server
yarn global add prettier import-js
yarn global add vscode-html-languageserver-bin
yarn global add vscode-css-languageserver-bin

# html / css
gem install specific_install
gem specific_install https://github.com/brigade/scss-lint.git
gem specific_install https://github.com/Sweetchuck/scss_lint_reporter_checkstyle.git
yarn global add vscode-css-languageserver-bin
yarn global add js-beautify

# elm
nix-env --install elm

# python
pip install --user pynvim
pip install --user flake8
pip install --user yapf
pip install --user autoflake
pip install --user isort
pip install --user coverage
pip install --user 'python-language-server[all]'
pip install --uesr 'ptvsd>=4.2'
pip install --user pyls-isort
pip install --user pyls-mypy
pip install --user importmagic
pip install --user epc
pip install --user black
# pip install --user cython
# pip install --user scikit-learn
pip install --user jupyter_contrib_nbextensions
jupyter contrib nbextension install --user

ln -fs "${HOME}"/.dotfiles/lang/mypy     "${HOME}"/.config/mypy
ln -fs "${HOME}"/.dotfiles/lang/pylintrc "${HOME}"/.config/pylintrc

# ruby
gem install solargraph
gem install pry
gem install sqlint

# crystal
nix-env --install crystal
nix-env --install icr

# php
nix-env --install php-composer
yarn global add intelephense
