#!/bin/bash

# rust
rustup self update
rustup update
rustup component add rls
rustup component add rust-analysis
rustup component add rust-src
rustup component add rustfmt
rustup component add clippy
rustup completions zsh > "${HOME}/.zfunc/_rustup"

# Golang
GO111MODULE=on go get -v golang.org/x/tools/gopls@latest
GO111MODULE=on CGO_ENABLED=0 go get -v -trimpath -ldflags '-s -w' github.com/golangci/golangci-lint/cmd/golangci-lint
go get -u golang.org/x/tools/cmd/godoc
go get -u golang.org/x/tools/cmd/goimports
go get -u golang.org/x/tools/cmd/gorename
go get -u golang.org/x/tools/cmd/guru
go get -u github.com/alecthomas/gometalinter
go get -u github.com/cweill/gotests/...
go get -u github.com/davidrjenni/reftools/cmd/fillstruct
go get -u github.com/fatih/gomodifytags
go get -u github.com/go-delve/delve/cmd/dlv
go get -u github.com/godoctor/godoctor
go get -u github.com/haya14busa/gopkgs/cmd/gopkgs
go get -u github.com/josharian/impl
go get -u github.com/mdempsky/gocode
go get -u github.com/rogpeppe/godef
go get -u github.com/zmb3/gogetdoc

# python
pip install --user --upgrade pip
pip list --user --outdated \
  | tail -n +3 \
  | grep -v 'jedi' \
  | awk '{print $1}' \
  | xargs pip install --user --upgrade

# ruby
gem update "$(gem outdated | cut -d ' ' -f 1)"

# node
yarn global upgrade
