#!/bin/bash

/bin/bash "${HOME}/.dotfiles/lang/script/rust"
/bin/bash "${HOME}/.dotfiles/lang/script/golang"

# python
pip install --user --upgrade pip
pip list --user --outdated \
  | tail -n +3 \
  | grep -v 'jedi' \
  | awk '{print $1}' \
  | xargs pip install --user --upgrade

# ruby
gem update "$(gem outdated | cut -d ' ' -f 1)"

# node
yarn global upgrade
