#!/bin/bash

# rust
rustup self update
rustup update
rustup component add rls-preview
rustup component add rust-analysis
rustup component add rust-src
rustup completions zsh > ~/.zfunc/_rustup

cargo install-update -a

# Golang
go get -u -v github.com/golang/dep/cmd/dep
go get -u -v github.com/nsf/gocode
go get -u -v github.com/rogpeppe/godef
go get -u -v golang.org/x/tools/cmd/guru
go get -u -v golang.org/x/tools/cmd/gorename
go get -u -v golang.org/x/tools/cmd/goimports
go get -u -v github.com/alecthomas/gometalinter
gometalinter --install --update
go get -u -v github.com/godoctor/godoctor
go install github.com/godoctor/godoctor
go get -u -v github.com/fatih/gomodifytags

