#!/bin/bash

# emacs
brew tap d12frosted/emacs-plus
brew install emacs-plus

# spacemacs
if [ ! -e ${HOME}/.emacs.d ]; then
    git clone https://github.com/syl20bnr/spacemacs ~/.emacs.d
    cd .emacs.d && git checkout -b develop origin/develop
fi

# neovim
brew install neovim

if [ ! -e ${HOME}/.config ]; then
    mkdir ${HOME}/.config
fi

if [ ! -e ${HOME}/.dotfiles/editor/dein ]; then
    mkdir ${HOME}/.dotfiles/editor/dein
    curl https://raw.githubusercontent.com/Shougo/dein.vim/master/bin/installer.sh > installer.sh
    sh ./installer.sh  ${HOME}/.dotfiles/editor/dein/repo
    rm ./installer.sh

fi
