#!/bin/bash

mkdir -p "${XDG_CONFIG_HOME}"

spacemacsdir="${XDG_CONFIG_HOME}/spacemacs.emacs.d"
doomemacsdir="${XDG_CONFIG_HOME}/doom.emacs.d"

# spacemacs
if [ ! -e "${spacemacsdir}" ]; then
    git clone https://github.com/syl20bnr/spacemacs "${spacemacsdir}"
    (cd "${spacemacsdir}" && git checkout -b develop origin/develop)
fi

# doom emacs
if [ ! -e "${doomemacsdir}" ]; then
    git clone https://github.com/hlissner/doom-emacs "${doomemacsdir}"
    ln -fs "${doomemacsdir}" "${XDG_CONFIG_HOME}/emacs"
    "${XDG_CONFIG_HOME}/emacs/bin/doom install"
fi

# spacevim
if [ ! -e "${HOME}/.dotfiles/editor/dein" ]; then
    mkdir -p "${HOME}/.dotfiles/editor/dein"
    curl https://raw.githubusercontent.com/Shougo/dein.vim/master/bin/installer.sh > installer.sh
    sh ./installer.sh "${XDG_CACHE_HOME}/dein"
    rm ./installer.sh
fi
curl -sLf https://spacevim.org/install.sh | bash

ln -fs "${HOME}/.dotfiles/editor/spacemacs"    "${HOME}/.spacemacs"
ln -fs "${HOME}/.dotfiles/editor/doom"         "${XDG_CONFIG_HOME}/doom"
ln -fs "${HOME}/.dotfiles/editor/nvim"         "${XDG_CONFIG_HOME}/nvim"
ln -fs "${HOME}/.dotfiles/editor/spacevim"     "${HOME}/.SpaceVim.d"
ln -fs "${HOME}/.dotfiles/editor/editorconfig" "${HOME}/.editorconfig"
ln -fs "${HOME}/.config/spacemacs.emacs.d"     "${XDG_CONFIG_HOME}/emacs"
