#!/bin/bash

if [[ "${OS_TYPE}" == "macos" ]]; then
  brew cask install emacs
  brew install neovim
  brew cask install visual-studio-code
else
  nix-env --install emacs
  nix-env --install neovim
fi

mkdir -p "${HOME}/.config"

# spacemacs
if [ ! -e "${HOME}/.config/spacemacs.emacs.d" ]; then
    git clone https://github.com/syl20bnr/spacemacs ~/.config/spacemacs.emacs.d
    (cd "${HOME}/.config/.spacemacs.emacs.d" && git checkout -b develop origin/develop)
fi

# doom emacs
if [ ! -e "${HOME}/.config/doom.emacs.d" ]; then
    git clone https://github.com/hlissner/doom-emacs ~/.config/doom.emacs.d
    ln -fs "${HOME}/.config/doom.emacs.d" "${HOME}/.emacs.d"
    ~/.emacs.d/bin/doom install
fi

# spacevim
if [ ! -e "${HOME}/.dotfiles/editor/dein" ]; then
    mkdir -p "${HOME}/.dotfiles/editor/dein"
    curl https://raw.githubusercontent.com/Shougo/dein.vim/master/bin/installer.sh > installer.sh
    sh ./installer.sh "${HOME}/.cache/dein"
    rm ./installer.sh
fi
curl -sLf https://spacevim.org/install.sh | bash

ln -fs "${HOME}/.dotfiles/editor/spacemacs"    "${HOME}/.spacemacs"
ln -fs "${HOME}/.dotfiles/editor/doom"         "${HOME}/.config/doom"
ln -fs "${HOME}/.dotfiles/editor/nvim"         "${HOME}/.config/nvim"
ln -fs "${HOME}/.dotfiles/editor/spacevim"     "${HOME}/.SpaceVim.d"
ln -fs "${HOME}/.dotfiles/editor/editorconfig" "${HOME}/.editorconfig"
ln -fs "${HOME}/.config/spacemacs.emacs.d"     "${HOME}/.emacs.d"
